"""add session closed at

Revision ID: 5828fdf8867f
Revises: e8820c937eb3
Create Date: 2019-02-05 10:28:40.255746

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5828fdf8867f'
down_revision = 'e8820c937eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('session_closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'session_closed_at')
    # ### end Alembic commands ###
