"""base

Revision ID: e8820c937eb3
Revises: 
Create Date: 2019-02-05 10:18:55.546259

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e8820c937eb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer',
                    sa.Column('serial_number', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('pos_key', sa.String(length=32), nullable=True),
                    sa.Column('pos_secret', sa.String(length=32), nullable=True),
                    sa.Column('devname', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('serial_number'),
                    sa.UniqueConstraint('pos_key'),
                    sa.UniqueConstraint('pos_secret')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer')
    # ### end Alembic commands ###
